### ISSUE TITLE
NullReferenceException MigrationHashHelper

### ISSUE THREAD

**Issue by michalciolek** [Weingartner/Migrations.Json.Net#12]
1) Change Migratable class
2) Get Analyzer error
3) I want fix Analyzer error by `CTRL+.` I get this error:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Weingartner.Json.Migration.Roslyn.MigrationHashHelper.<>c.<GetMigrationMethods>b__7_0(IMethodSymbol m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Weingartner.Json.Migration.Roslyn.MigrationHashHelper.GetMigrationMethods(ITypeSymbol typeSymbol)
   at async Weingartner.Json.Migration.Roslyn.AddMigrationMethodCodeFixProvider.AddMigrationMethod(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

Correcting migration hash works but I cannot create migration method...

My environment:
Windows 10
Visual Studio 16.6.0
.NET Framework 4.8
Migrations.Json.Net 2.1.2

**Comment by FlorianAuinger** [comment]
with v2.1.9 some NullReference Exceptions in the analyzer have been fixed.

**Comment by michalciolek** [comment]
Thanks! With 2.1.9 everything works well :)
